diff --git a/Makefile b/Makefile
index c261974..2467866 100644
--- a/Makefile
+++ b/Makefile
@@ -1,10 +1,10 @@
 prefix=/usr/local
 bindir=$(prefix)/bin
 datarootdir=$(prefix)/share
-
+CC?=gcc
 all:
-	gcc pacman.c     -o pacman     -DDATAROOTDIR=\"$(datarootdir)\" $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -lncurses
-	gcc pacmanedit.c -o pacmanedit -DDATAROOTDIR=\"$(datarootdir)\" $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -lncurses
+	${CC} pacman.c     -o pacman     -DDATAROOTDIR=\"$(datarootdir)\" $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -lncurses
+	${CC} pacmanedit.c -o pacmanedit -DDATAROOTDIR=\"$(datarootdir)\" $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -lncurses
 
 install:	all
 	mkdir -p $(DESTDIR)$(bindir)
